name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'macos-10.15']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Pre
        run: |
          brew update && brew install bash libtool automake m4 yasm nasm make cmake mercurial ninja
      - name: script
        run: |
          curl -sL https://github.com/rokibhasansagar/test_ff/raw/main/test.sh | bash
